"""empty message

Revision ID: 09d40b8cca29
Revises: 
Create Date: 2020-09-16 14:21:52.820117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d40b8cca29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tickers', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.phone_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickers')
    op.drop_table('users')
    # ### end Alembic commands ###
